CREATE TABLE IF NOT EXISTS resource_categories (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_resource_categories_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;